cluster: "sbatch --parsable"
cluster-status: "slurm-status.py {jobid}"
jobscript: "slurm/sbatch-jobscript.sh"

jobs: 100
latency-wait: 60
use-conda: true
rerun-incomplete: true
keep-going: true
restart-times: 3




